### ISSUE TITLE
How to pass calls to users

### ISSUE THREAD

**Issue by joshuaalayon** [serfreeman1337/asterlink#23]
SuiteCRM 8.5 
The asterisk is running on freepbx 17

Asterlink can see the calls... I think the issue is in the SuiteCRM Asterisk Extension, not being picked up by the FreePBX extension

Let me know if any logs would help please

**Comment by serfreeman1337** [comment]
For freepbx17 you need to add "trunk-dial-with-exten" and "dialOne-with-exten" contexts  in the config like that:
```yaml
dialplan:
  incoming_context:
  - from-pstn
  outgoing_context:
  - macro-dialout-trunk
  - trunk-dial-with-exten
  ext_context:
  - macro-dial-one
  - macro-dial
  - dialOne-with-exten
  dial_context: from-internal
```

`987:1` is a <extension>:<user id> mapping

**Comment by joshuaalayon** [comment]
Unfortunately, it still isn't passing calls to SuiteCRM, at least that I can see. Maybe I need something else installed on SuiteCRM, the only call module I have is from this one, otherwise the SuiteCRM install is completely fresh.

This is what I see when running asterlink from cli during a call, not sure if it helps.

./asterlink

INFO[0000] AsterLink
INFO[0000] Setting log level                             fields.level=debug
INFO[0000] Using SuiteCRM Connector
INFO[0000] User list updated                             suite=true users="map[987:1]"
INFO[0000] Enabling web server                           addr="0.0.0.0:5678" suite=true
INFO[0000] Established connection with AMI               fields.msg="Asterisk Call Manager/10.0.0"
DEBU[0007] MixMonitor                                    lid=1735708951.5 rec=2025/01/01/in-1**********-1**********-20250101-002231-1735708951.5.wav uid=1735708951.5
DEBU[0091] Clear recording                               lid=1735708951.5 uid=1735708951.5

**Comment by serfreeman1337** [comment]
What is the trunk context on freepbx ? It must be `from-pstn`.
![image](https://github.com/user-attachments/assets/d4965f46-fad8-45a0-b2bb-0f77d996aa20)

**Comment by joshuaalayon** [comment]
from-pstn-toheader

I have already tried changing the incoming context in conf.yml as well, to no avail, same behavior, same thing in Asterlink CLI

**Comment by serfreeman1337** [comment]
I guess your trunk provider places calls to "s" extension and so that why you need to use `from-pstn-toheader`.

The problem is the "s" extension is filtered here:
https://github.com/serfreeman1337/asterlink/blob/302e7f92a586b528383f8a43cb1e5cc4e69273b8/ami_connector.go#L197

You can try to "fix" it by hardcoding DID value in the code like that:
```diff
// incoming call
func (a *amiConnector) onNewchannel(e map[string]string) {
+	if a.isContext(e["Context"], a.cfg.DP.In) && e["Exten"] == "s" {
+		e["Exten"] = "1234567MYDID"
+	}
	
	if /*_, ok := IncomingContext[e["Context"]]; !ok || */ e["Exten"] == "s" { // TODO: review this 's'!
		return
	}
```

You can also specify both `from-pstn` and `from-pstn-toheader` contexts in the config.
```yaml
dialplan:
  incoming_context:
  - from-pstn
  - from-pstn-toheader
  outgoing_context:
  - macro-dialout-trunk
  - trunk-dial-with-exten
  ext_context:
  - macro-dial-one
  - macro-dial
  - dialOne-with-exten
  dial_context: from-internal
```

Is that trunk with registration ? If so, can you check if changing trunk's "Contact user" to your DID will ask the trunk provider to send calls to that extension and not "s" ? 
![image](https://github.com/user-attachments/assets/c0964591-67d8-4bfb-a75f-55d1b87f64b1)

**Comment by joshuaalayon** [comment]
Changing trunk's "Contact user" to DID made the call pop up in the log! No need to edit ami_connector.go. Is it possible to have calls show up in the browser or to be able to click to call back?

**Comment by serfreeman1337** [comment]
Check [README_suitecrm.md](https://github.com/serfreeman1337/asterlink/blob/master/README_suitecrm.md).
For call card and click2call you need to configure "Endpoint URL" for SuiteCRM Module.
`http://<asterlink connector server ip address>:<asterlink connector listen port>`

**Comment by joshuaalayon** [comment]
It is configured according to the example

suitecrm:
  url: https://SuiteCRM base URL in https is the issue that this url is https?
  endpoint_token: same token as Asterlink settings in SuiteCRM GUI
  endpoint_addr: "127.0.0.1:5678"
  
 http://127.0.0.1:5678 is address given in gui and endpoint token is same in both gui and conf.yml

**Comment by serfreeman1337** [comment]
Is asterlink and suitecrm on the same server ? If so, enable proxy mode in gui.

Address given in gui will be used by both suitecrm and users browsers to connect to asterlink, so it must be accessible for them.

With current setup:

Without proxy mode enabled:
User's browser -> http://127.0.0.1:5678

With proxy mode enabled:
User's browser -> https://SuiteCRM -> http://127.0.0.1:5678

**Comment by joshuaalayon** [comment]
proxy mode is enabled and I think working because calls are logging

ext= only shows up in Asterlink CLI after "Dial stop"
so the extension is only being passed, if I hang up the remote phone, calling into the pbx. If I answer the extension on a hard phone, the extension number is not passed, basically nothing passes the extension number to Asterlink CLI, until I hang up the phone that is calling into the pbx. not sure if that helps.

**Comment by serfreeman1337** [comment]
Is your extension in `from-internal` context ?
Also note: there is no support for Follow-Me.

I will need AMI dump to debug this issue.

AMI dump can contain some private info, like CallerID and DID numbers
You can send it to my email.

* Run:
  [ami-dump.zip](https://github.com/user-attachments/files/18284959/ami-dump.zip)
  `./ami-dump -c ami_host:5038 -u ami_user -p ami_pass | tee -i dump.txt`
* Answer a call and hangup.
* AMI events will be in the `dump.txt` file.

**Comment by joshuaalayon** [comment]
I emailed you it. Big file!

**Comment by serfreeman1337** [comment]
For ring groups you need to also add `dial-with-exten` to `ext_context`:
```
dialplan:
  incoming_context:
  - from-pstn
  - from-pstn-toheader
  outgoing_context:
  - macro-dialout-trunk
  - trunk-dial-with-exten
  ext_context:
  - macro-dial-one
  - macro-dial
  - dialOne-with-exten
  - dial-with-exten
  dial_context: from-internal
```
